name: playtech_transmitter_app
description: "Playtech Transmitter App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0-113.0.dev <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  get: ^4.7.2
  intl: ^0.20.2
  macos_window_utils: ^1.7.1
  web_socket_channel: ^3.0.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/font/

  fonts:
    - family: OpenSans
      fonts:
        - asset: asset/font/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: asset/font/OpenSans-VariableFont_wdth,wght.ttf
    - family: LibreBaskerville
      fonts:
        - asset: asset/font/LibreBaskerville-Regular.ttf
        - asset: asset/font/LibreBaskerville-Bold.ttf
          weight: 700
        - asset: asset/font/LibreBaskerville-Italic.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: asset/font/Montserrat-Italic-VariableFont_wght.ttf
        - asset: asset/font/Montserrat-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: asset/font/Poppins-Regular.ttf
        - asset: asset/font/Poppins-Medium.ttf
        - asset: asset/font/Poppins-Black.ttf
          weight: 500
        - asset: asset/font/Poppins-Bold.ttf
          weight: 900
    - family: imprint
      fonts:
        - asset: asset/font/imprint-mt-shadow-1/ImprintMTShadow.ttf
    - family: derrida
      fonts:
        - asset: asset/font/derrida-font/Derrida-wvM6.ttf

    - family: Bungee
      fonts:
        - asset: asset/font/Bungee-Regular.ttf
    - family: Rubik
      fonts:
        - asset: asset/font/Rubik-VariableFont_wght.ttf
        - asset: asset/font/Rubik-Italic-VariableFont_wght.ttf
    - family: Archivo
      fonts:
        - asset: asset/font/Archivo-Italic-VariableFont_wdth,wght.ttf
        - asset: asset/font/Archivo-VariableFont_wdth,wght.ttf
    - family: YoureGone
      fonts:
        - asset: asset/font/YoureGone.otf
    - family: Arcane
      fonts:
        - asset: asset/font/arcane.ttf
    - family: SFPro
      fonts:
        - asset: asset/font/SF-Pro-Display-Medium.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
